---
abstract: 'Swish3 Xapian backend'
author:
  - 'Peter Karman <karman at cpan dot org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SWISH-Prog-Xapian
no_index:
  directory:
    - t
    - inc
requires:
  Path::Class::File::Lockable: 0
  SWISH::3: 1.000001
  SWISH::Prog: 0.54
  Search::Xapian: 0
  Sort::SQL: 0
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SWISH-Prog-Xapian
  homepage: http://dev.swish-e.org/wiki/perl
  license: http://dev.perl.org/licenses/
  repository: http://svn.swish-e.org/perl/SWISH-Prog-Xapian/
version: 0.09
